# Generated by Django 5.2.5 on 2025-09-06 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Saved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='posts.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved',
                'verbose_name_plural': 'Saves',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['post'], name='saved_post_idx'), models.Index(fields=['user'], name='saved_user_idx'), models.Index(fields=['created_at'], name='saved_created_at_idx')],
                'unique_together': {('user', 'post')},
            },
        ),
    ]
